version: '3'
services:
  #build:
    #  context: .
  astronautjs-nodejs:
    image: astronautjs/api-node
    container_name: astronautjs-nodejs
    hostname: astronautjs-nodejs
    restart: always
    environment:
      - VIRTUAL_HOST=astronautjs.alexslx.xyz
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=astronautjs.alexslx.xyz
      - LETSENCRYPT_EMAIL=alexslxbr+letsencrypt@gmail.com
    links:
      - astronautjs-mongo

  astronautjs-mongo:
    image: mongo
    container_name: astronautjs-mongo
    hostname: astronautjs-mongo
    restart: always
    volumes:
      - V:\Docker\Volumes\astronautjs-mongo\data:/data
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo 127.0.0.1:27017/astronautjs --quiet"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    external:
      name: nginx-proxy-network